#!/bin/sh

bash sourceWS $1

function terminal () { xdotool key ctrl+alt+t; sleep 0.5; }

function Enter () { xdotool key KP_Enter; sleep 0.5; }

# step1 = "roscore"
# step2 = "ssh -oSendEnv=ROS_MASTER_URI student@station"
# step3 = "roslaunch franka_control franka_control.launch robot_ip:=robot.franka.de"
# step4 = "roslaunch group4 launch_robot.launch"
# step5 = "rosrun group4 TaskMaster"

terminal;
xdotool type "roscore";
Enter;
terminal;
xdotool type "ssh -oSendEnv=ROS_MASTER_URI student@station";
sleep 3;
xdotool type "roslaunch franka_control franka_control.launch robot_ip:=robot.franka.de";
Enter;
terminal;
xdotool type "roslaunch group4 launch_robot.launch";
Enter;
terminal;
xdotool type "rosrun group4 TaskMaster";
Enter;
bash wsSourceRemove;