#!/bin/sh

bash sourceWS $1

gnome-terminal -e 'sh -c "ssh -oSendEnv=ROS_MASTER_URI student@station ; roslaunch franka_control franka_control.launch robot_ip:=robot.franka.de"'&
# sleep 1s
xterm -title 'sh -c "roslaunch group4 launch_robot.launch"'&
# sleep 3s
xterm -title 'sh -c "rosrun group4 TaskMaster"'&

bash wsSourceRemove
